/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package resturantmanagement.order;

import resturantmanagement.Products.AddProduct;
import resturantmanagement.dashboard;
import resturantmanagement.model.Cart;
import resturantmanagement.model.CartProducts;
import resturantmanagement.model.Item;
import resturantmanagement.model.ManageOrder;
import resturantmanagement.model.ManageOrderDetails;
import resturantmanagement.model.ManageProduct;
import resturantmanagement.model.ManageStaffDetails;
import resturantmanagement.model.Order;
import resturantmanagement.model.OrderLine;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class OrderManagement extends javax.swing.JFrame {
    private final ManageOrderDetails manageOrderDetails;

    /**
     * Creates new form OrderManagement
     */
    public OrderManagement() {
        this.initComponents();
        this.manageOrderDetails = new ManageOrderDetails();
        
        //load Products in the table
        manageOrderDetails.seeData(jTable1);      
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        dash = new javax.swing.JButton();
        btnOrder1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnAddToCart = new javax.swing.JButton();
        tot = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        orderdetails = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        text.setEditable(false);
        text.setBackground(new java.awt.Color(204, 204, 204));
        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setPreferredSize(new java.awt.Dimension(1000, 636));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 29, 368, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product id :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 153, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 219, -1, -1));

        txtqty.setBackground(new java.awt.Color(204, 204, 204));
        txtqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 213, 360, 30));

        txtname.setBackground(new java.awt.Color(204, 204, 204));
        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 147, 360, 30));

        dash.setBackground(new java.awt.Color(0, 153, 255));
        dash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dash.setForeground(new java.awt.Color(255, 255, 255));
        dash.setText("Dashboard");
        dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashActionPerformed(evt);
            }
        });
        getContentPane().add(dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 363, -1, 56));

        btnOrder1.setBackground(new java.awt.Color(0, 153, 255));
        btnOrder1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOrder1.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder1.setText("ORDER");
        btnOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrder1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 43, 111, 56));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product  id", "Quantity", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 29, 332, 92));

        btnAddToCart.setBackground(new java.awt.Color(0, 153, 255));
        btnAddToCart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddToCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 296, -1, 56));

        tot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tot.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 254, 80, 40));

        orderdetails.setColumns(20);
        orderdetails.setRows(5);
        orderdetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane4.setViewportView(orderdetails);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 132, 361, 309));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addContainerGap(941, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel5)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashActionPerformed
        // Go to Dashboard
            dashboard dash = new dashboard();
            this.setVisible(false);
            dash.setVisible(true);
    }//GEN-LAST:event_dashActionPerformed

    private void btnOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrder1ActionPerformed
        // Creates Receipt of the Order
        try{
            
        orderdetails.append("\t \t ORDER DETAILS \n \n"+
                "Product Id : "+txtname.getText()+
                "\n=========================================\n"+
                "Product Qty: "+txtqty.getText()+"\n"+
                        "Total :"+tot.getText()+"\n"
                
                );
        }
        catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_btnOrder1ActionPerformed
 int total;
    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed

        //Check which item is selected
       checkItem();
       
       Order order = new Order(Integer.parseInt(txtname.getText()), Integer.parseInt(txtqty.getText()),Integer.parseInt(tot.getText()));        
      //Called AddtoCart method which inserts selected prodcut in cart
       manageOrderDetails.AddtoCart(order);
    }//GEN-LAST:event_btnAddToCartActionPerformed


  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OrderManagement().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnOrder1;
    private javax.swing.JButton dash;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea orderdetails;
    private javax.swing.JTextArea text;
    private javax.swing.JLabel tot;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables

    private void checkItem() {
         int id = Integer.parseInt(txtname.getText());
         if(id== 1){
                int qty = Integer.parseInt(txtqty.getText());
                int price =500;
                total = qty*price;
                tot.setText(""+total);
            }
         if(id== 2){
                int qty = Integer.parseInt(txtqty.getText());
                int price =300;
                total = qty*price;
                tot.setText(""+total);
            }
         if(id== 3){
                int qty = Integer.parseInt(txtqty.getText());
                int price =50;
                total = qty*price;
                tot.setText(""+total);
            }
         if(id== 4){
                int qty = Integer.parseInt(txtqty.getText());
                int price =150;
                total = qty*price;
                tot.setText(""+total);
            }
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[]{
          txtname.getText(),txtqty.getText(),total,
        });
    }
}
